-- 코드를 입력하세요
SELECT
    *
    # A.PRICE_GROUP
    # COUNT(*) AS PRODUCTS
FROM
    (
    SELECT 
        (PRICE DIV 10000) * 10000 AS PRICE_GROUP,    
        COUNT(*) AS PRODUCTS
    FROM PRODUCT
    GROUP BY PRICE_GROUP
    ) AS A
ORDER BY
    PRICE_GROUP
